In [1]:
import numpy as np
import pandas as pd

In [2]:
#读入各数据

In [3]:
train=pd.read_csv(r"E:\学习资料\人工智能\大数据竞赛\data_format1\data_format1\train_format1.csv").drop_duplicates()
train.head(5)

user_id  merchant_id  label
0    34176         3906      0
1    34176          121      0
2    34176         4356      1
3    34176         2217      0
4   230784         4818      0

In [4]:
test=pd.read_csv(r"E:\学习资料\人工智能\大数据竞赛\data_format1\data_format1\test_format1.csv")
test.head(5)

user_id  merchant_id  prob
0   163968         4605   NaN
1   360576         1581   NaN
2    98688         1964   NaN
3    98688         3645   NaN
4   295296         3361   NaN

In [5]:
user_info=pd.read_csv(r"E:\学习资料\人工智能\大数据竞赛\data_format1\data_format1\user_info_format1.csv")
user_info.head(5)

user_id  age_range  gender
0   376517        6.0     1.0
1   234512        5.0     0.0
2   344532        5.0     0.0
3   186135        5.0     0.0
4    30230        5.0     0.0

In [6]:
user_log=pd.read_csv(r"E:\学习资料\人工智能\大数据竞赛\data_format1\data_format1\user_log_format1.csv").rename(columns={"seller_id":"merchant_id"})
user_log.head()

user_id  item_id  cat_id  merchant_id  brand_id  time_stamp  action_type
0   328862   323294     833         2882    2661.0         829            0
1   328862   844400    1271         2882    2661.0         829            0
2   328862   575153    1271         2882    2661.0         829            0
3   328862   996875    1271         2882    2661.0         829            0
4   328862  1086186    1271         1253    1049.0         829            0

In [7]:
#合并训练集，测试集和用户信息

In [8]:
train=train.merge(user_info,on=["user_id"])
test=test.merge(user_info,on=["user_id"])

In [9]:
train.head(5)

user_id  merchant_id  label  age_range  gender
0    34176         3906      0        6.0     0.0
1    34176          121      0        6.0     0.0
2    34176         4356      1        6.0     0.0
3    34176         2217      0        6.0     0.0
4   230784         4818      0        0.0     0.0

In [10]:
test.head(5)

user_id  merchant_id  prob  age_range  gender
0   163968         4605   NaN        0.0     0.0
1   360576         1581   NaN        2.0     2.0
2    98688         1964   NaN        6.0     0.0
3    98688         3645   NaN        6.0     0.0
4   295296         3361   NaN        2.0     1.0

In [11]:
user_info_log=user_log.merge(user_info,on=["user_id"])

In [12]:
user_info_log.head(20)

user_id  item_id  cat_id  merchant_id  brand_id  time_stamp  action_type  \
0    328862   323294     833         2882    2661.0         829            0   
1    328862   844400    1271         2882    2661.0         829            0   
2    328862   575153    1271         2882    2661.0         829            0   
3    328862   996875    1271         2882    2661.0         829            0   
4    328862  1086186    1271         1253    1049.0         829            0   
5    328862   623866    1271         2882    2661.0         829            0   
6    328862   542871    1467         2882    2661.0         829            0   
7    328862   536347    1095          883    1647.0         829            0   
8    328862   364513    1271         2882    2661.0         829            0   
9    328862   575153    1271         2882    2661.0         829            0   
10   328862   239288     602          420    4953.0         801            0   
11   328862   950862     962         4605    7622.0         801            0   
12   328862   262500     602          420    4953.0         801            0   
13   328862  1064265     614         4605    7622.0         801            0   
14   328862   809148     602          420    4953.0         801            0   
15   328862   197239     602          420    4953.0         801            0   
16   328862    43367    1505         3828    1446.0         526            0   
17   328862   844535     302         3354     883.0         526            0   
18   328862   886633    1505         3828    1446.0         526            0   
19   328862    81766     614         4605    7622.0         709            2   

    age_range  gender  
0         6.0     1.0  
1         6.0     1.0  
2         6.0     1.0  
3         6.0     1.0  
4         6.0     1.0  
5         6.0     1.0  
6         6.0     1.0  
7         6.0     1.0  
8         6.0     1.0  
9         6.0     1.0  
10        6.0     1.0  
11        6.0     1.0  
12        6.0     1.0  
13        6.0     1.0  
14        6.0     1.0  
15        6.0     1.0  
16        6.0     1.0  
17        6.0     1.0  
18        6.0     1.0  
19        6.0     1.0

In [13]:
user_info_log.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1048575 entries, 0 to 1048574
Data columns (total 9 columns):
user_id        1048575 non-null int64
item_id        1048575 non-null int64
cat_id         1048575 non-null int64
merchant_id    1048575 non-null int64
brand_id       1047248 non-null float64
time_stamp     1048575 non-null int64
action_type    1048575 non-null int64
age_range      1048450 non-null float64
gender         1046301 non-null float64
dtypes: float64(3), int64(6)
memory usage: 80.0 MB


In [14]:
user_info_log.isnull().sum(axis=0)

user_id           0
item_id           0
cat_id            0
merchant_id       0
brand_id       1327
time_stamp        0
action_type       0
age_range       125
gender         2274
dtype: int64

In [15]:
age_range=user_info_log.loc[:,"age_range"].values.reshape(-1,1)
age_range[:5]

array([[6.],
       [6.],
       [6.],
       [6.],
       [6.]])

In [16]:
from sklearn.impute import SimpleImputer
imp_0=SimpleImputer(strategy="constant",fill_value=0)
imp_0=imp_0.fit_transform(age_range)
imp_0[:5]

array([[6.],
       [6.],
       [6.],
       [6.],
       [6.]])

In [17]:
user_info_log.loc[:,"age_range"]=imp_0

In [18]:
user_info_log.isnull().sum(axis=0)

user_id           0
item_id           0
cat_id            0
merchant_id       0
brand_id       1327
time_stamp        0
action_type       0
age_range         0
gender         2274
dtype: int64

In [19]:
gender=user_info_log.loc[:,"gender"].values.reshape(-1,1)
gender[:5]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [20]:
imp_2=SimpleImputer(strategy="constant",fill_value=2)
imp_2=imp_2.fit_transform(gender)
imp_2[:5]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [21]:
user_info_log.loc[:,"gender"]=imp_2

In [22]:
user_info_log.isnull().sum(axis=0)

user_id           0
item_id           0
cat_id            0
merchant_id       0
brand_id       1327
time_stamp        0
action_type       0
age_range         0
gender            0
dtype: int64

In [23]:
user_info_log=user_info_log.dropna(subset=["brand_id"])

In [24]:
user_info_log.isnull().sum(axis=0)

user_id        0
item_id        0
cat_id         0
merchant_id    0
brand_id       0
time_stamp     0
action_type    0
age_range      0
gender         0
dtype: int64

In [25]:
user_info_log.head()

user_id  item_id  cat_id  merchant_id  brand_id  time_stamp  action_type  \
0   328862   323294     833         2882    2661.0         829            0   
1   328862   844400    1271         2882    2661.0         829            0   
2   328862   575153    1271         2882    2661.0         829            0   
3   328862   996875    1271         2882    2661.0         829            0   
4   328862  1086186    1271         1253    1049.0         829            0   

   age_range  gender  
0        6.0     1.0  
1        6.0     1.0  
2        6.0     1.0  
3        6.0     1.0  
4        6.0     1.0

In [26]:
#查看训练集中标签种类有哪些

In [27]:
from sklearn.preprocessing import LabelEncoder
y=train.iloc[:,2]
le=LabelEncoder()
le=le.fit(y)

In [28]:
le.classes_

array([0, 1], dtype=int64)

In [29]:
#检查信息中心年龄信息，发现没有小于18岁的购物记录

In [30]:
y=user_info_log.iloc[:,7]
le=LabelEncoder()
le=le.fit(y)
le.classes_

array([0., 2., 3., 4., 5., 6., 7., 8.])

In [31]:
#特征一：用户每个月产生动作的次数

In [32]:
#从记录中提取月份和天
user_info_log['month']=user_info_log['time_stamp']//100
#user_info_log['day']=user_info_log['time_stamp']%100
#del user_info_log['time_stamp']

In [33]:
user_info_log[1000:1005]

user_id  item_id  cat_id  merchant_id  brand_id  time_stamp  \
1000   149002   754044    1213         3736    3125.0         521   
1001   149002   871086     368         1190    1500.0        1107   
1002   149002  1074027     964         3791    1500.0        1111   
1003   149002  1099256     606         4606    4383.0         820   
1004   149002   989660     577         3791    1500.0        1111   

      action_type  age_range  gender  month  
1000            0        5.0     2.0      5  
1001            0        5.0     2.0     11  
1002            0        5.0     2.0     11  
1003            0        5.0     2.0      8  
1004            0        5.0     2.0     11

In [34]:
#size() 返回每个分组的元素个数
t=user_info_log.groupby(['user_id','month']).size().reset_index().rename(columns={0:'user_month_cnt'})
t.head()

user_id  month  user_month_cnt
0       16      9              26
1       16     10              15
2       16     11              26
3       19      7               6
4       19      9               2

In [35]:
#get_dummies类别变量向量化,pandas提供对one-hot编码的函数
t=pd.get_dummies(t,columns=['month'])

In [36]:
t.head()

user_id  user_month_cnt  month_5  month_6  month_7  month_8  month_9  \
0       16              26        0        0        0        0        1   
1       16              15        0        0        0        0        0   
2       16              26        0        0        0        0        0   
3       19               6        0        0        1        0        0   
4       19               2        0        0        0        0        1   

   month_10  month_11  
0         0         0  
1         1         0  
2         0         1  
3         0         0  
4         0         0

In [37]:
#计算每个用户每个月操作次数
for i in range(5,12,1):
    t['month_'+str(i)]*=t['user_month_cnt']

In [38]:
t=t.groupby(['user_id']).sum().reset_index()
t.head()

user_id  user_month_cnt  month_5  month_6  month_7  month_8  month_9  \
0       16              67        0        0        0        0       26   
1       19             113        0        0        6        0        2   
2      244             126       13        5        4       29        0   
3      259             193       12        0        0        1        0   
4      281              75        1        1        0       15       42   

   month_10  month_11  
0        15        26  
1         0       105  
2        22        53  
3         1       179  
4         1        15

In [39]:
t=t.rename(columns={'user_month_cnt':'user_sum','month_5':'user_month_5','month_6':'user_month_6','month_7':'user_month_7','month_8':'user_month_8','month_9':'user_month_9','month_10':'user_month_10','month_11':'user_month_11'})
t[:5]

user_id  user_sum  user_month_5  user_month_6  user_month_7  user_month_8  \
0       16        67             0             0             0             0   
1       19       113             0             0             6             0   
2      244       126            13             5             4            29   
3      259       193            12             0             0             1   
4      281        75             1             1             0            15   

   user_month_9  user_month_10  user_month_11  
0            26             15             26  
1             2              0            105  
2             0             22             53  
3             0              1            179  
4            42              1             15

In [40]:
#将特征放入训练集和测试集中
train=train.merge(t,on=['user_id'])
test=test.merge(t,on=['user_id'])

In [41]:
train[:5]

user_id  merchant_id  label  age_range  gender  user_sum  user_month_5  \
0   374400          302      0        5.0     1.0       278             1   
1   189312         1760      0        4.0     0.0       237             0   
2   189312         2511      0        4.0     0.0       237             0   
3    71808         4850      0        5.0     1.0       171             4   
4   342912          514      0        4.0     0.0        93            21   

   user_month_6  user_month_7  user_month_8  user_month_9  user_month_10  \
0            16            30            98            52             31   
1             0             0             0            14             72   
2             0             0             0            14             72   
3             1            43            22            36             24   
4            13            13             3            10             20   

   user_month_11  
0             50  
1            151  
2            151  
3             41  
4             13

In [42]:
user_info_log[:5]

user_id  item_id  cat_id  merchant_id  brand_id  time_stamp  action_type  \
0   328862   323294     833         2882    2661.0         829            0   
1   328862   844400    1271         2882    2661.0         829            0   
2   328862   575153    1271         2882    2661.0         829            0   
3   328862   996875    1271         2882    2661.0         829            0   
4   328862  1086186    1271         1253    1049.0         829            0   

   age_range  gender  month  
0        6.0     1.0      8  
1        6.0     1.0      8  
2        6.0     1.0      8  
3        6.0     1.0      8  
4        6.0     1.0      8

In [43]:
#用户其他特征
#1、用户查询相应mechant_id的次数
t=user_info_log.groupby(['user_id','merchant_id']).size()
t=t.reset_index().rename(columns={0:'user_search_the_merchant'})

In [44]:
t[:5]

user_id  merchant_id  user_search_the_merchant
0       16          574                         1
1       16          650                        19
2       16          760                         1
3       16         1140                         1
4       16         1435                        11

In [45]:
train=train.merge(t,on=["user_id","merchant_id"])
test=test.merge(t,on=["user_id","merchant_id"])

In [46]:
train[:5]

user_id  merchant_id  label  age_range  gender  user_sum  user_month_5  \
0   374400          302      0        5.0     1.0       278             1   
1   189312         1760      0        4.0     0.0       237             0   
2   189312         2511      0        4.0     0.0       237             0   
3    71808         4850      0        5.0     1.0       171             4   
4   342912          514      0        4.0     0.0        93            21   

   user_month_6  user_month_7  user_month_8  user_month_9  user_month_10  \
0            16            30            98            52             31   
1             0             0             0            14             72   
2             0             0             0            14             72   
3             1            43            22            36             24   
4            13            13             3            10             20   

   user_month_11  user_search_the_merchant  
0             50                        29  
1            151                        42  
2            151                        12  
3             41                         6  
4             13                         5

In [47]:
#2、用户查询物品，种类，商家，品牌总数

In [48]:
#agg函数，它提供基于列的聚合操作
#set() 函数创建一个无序不重复元素集，可进行关系测试，删除重复数据，还可以计算交集、差集、并集等
#lamba函数冒号之前是参数，式子本身是值
columns = ['item_id', 'cat_id', 'merchant_id', 'brand_id']
for col in columns:
    t = user_info_log.groupby(['user_id']).agg({col:lambda x:len(set(x))}).reset_index().rename(columns={col:'user_'+col+'_cnt'})
    train=train.merge(t,on=['user_id'])
    test=test.merge(t,on=['user_id'])

In [49]:
train[:5]

user_id  merchant_id  label  age_range  gender  user_sum  user_month_5  \
0   374400          302      0        5.0     1.0       278             1   
1   189312         1760      0        4.0     0.0       237             0   
2   189312         2511      0        4.0     0.0       237             0   
3    71808         4850      0        5.0     1.0       171             4   
4   342912          514      0        4.0     0.0        93            21   

   user_month_6  user_month_7  user_month_8  user_month_9  user_month_10  \
0            16            30            98            52             31   
1             0             0             0            14             72   
2             0             0             0            14             72   
3             1            43            22            36             24   
4            13            13             3            10             20   

   user_month_11  user_search_the_merchant  user_item_id_cnt  user_cat_id_cnt  \
0             50                        29               148               59   
1            151                        42               170               35   
2            151                        12               170               35   
3             41                         6                89               35   
4             13                         5                55               24   

   user_merchant_id_cnt  user_brand_id_cnt  
0                    57               62.0  
1                    49               45.0  
2                    49               45.0  
3                    54               50.0  
4                    37               37.0

In [50]:
#3、用户点击、购买、加入购物车、收藏总数
user_info_log[:5]

user_id  item_id  cat_id  merchant_id  brand_id  time_stamp  action_type  \
0   328862   323294     833         2882    2661.0         829            0   
1   328862   844400    1271         2882    2661.0         829            0   
2   328862   575153    1271         2882    2661.0         829            0   
3   328862   996875    1271         2882    2661.0         829            0   
4   328862  1086186    1271         1253    1049.0         829            0   

   age_range  gender  month  
0        6.0     1.0      8  
1        6.0     1.0      8  
2        6.0     1.0      8  
3        6.0     1.0      8  
4        6.0     1.0      8

In [51]:
t=user_info_log.groupby(['user_id','action_type']).size().reset_index()

In [52]:
t[:5]

user_id  action_type    0
0       16            0   63
1       16            2    4
2       19            0  101
3       19            2   10
4       19            3    2

In [53]:
t=pd.get_dummies(t,columns=['action_type'])

In [54]:
for i in range(0,4,1):
    t['action_type_'+str(i)]=t[0]*t['action_type_'+str(i)]

In [55]:
t=t.groupby(['user_id']).sum().reset_index()

In [56]:
del t[0]

In [57]:
t=t.rename(columns={'action_type_0':'点击总数','action_type_1':'加入购物车数','action_type_2':'购买总数','action_type_3':'收藏总数'})

In [58]:
train=train.merge(t,on=['user_id'])
test=test.merge(t,on=['user_id'])

In [59]:
train[2530:2550]

user_id  merchant_id  label  age_range  gender  user_sum  user_month_5  \
2530   115252         1890      0        4.0     0.0       158             1   
2531    49972         1679      0        4.0     0.0       609           138   
2532    49972         4173      0        4.0     0.0       609           138   
2533   394036          219      0        4.0     0.0        55             3   
2534    82996         1346      0        4.0     0.0        75            27   
2535   228916         1667      0        5.0     0.0        43             2   
2536   166453         2138      0        4.0     0.0       159             6   
2537   166453         1031      0        4.0     0.0       159             6   
2538   197173         1500      0        4.0     1.0         9             1   
2539    99382         1999      1        4.0     0.0       305             0   
2540    99382         2148      0        4.0     0.0       305             0   
2541   253750         1839      0        5.0     0.0       532            39   
2542    15670          826      0        5.0     0.0       234             3   
2543   344374         3609      0        3.0     1.0        37             7   
2544   344374         4033      1        3.0     1.0        37             7   
2545   347446         1318      0        4.0     0.0        25             0   
2546   224566         1056      0        4.0     0.0        16             2   
2547   358966          505      0        3.0     1.0        71             0   
2548   380983         3085      0        4.0     1.0        32             0   
2549   119863         4687      0        5.0     1.0        49             0   

      user_month_6  user_month_7  user_month_8  ...  user_month_11  \
2530             0             0             0  ...            150   
2531           108            61           117  ...             59   
2532           108            61           117  ...             59   
2533             3             0             2  ...             28   
2534             3             8             3  ...             22   
2535             3             0             0  ...             37   
2536            43            22            44  ...             20   
2537            43            22            44  ...             20   
2538             1             0             0  ...              6   
2539             5             2             1  ...            163   
2540             5             2             1  ...            163   
2541           125             8            56  ...             58   
2542            27             7            97  ...             45   
2543             0             3             4  ...              7   
2544             0             3             4  ...              7   
2545             0             0             0  ...             15   
2546             1             2             2  ...              4   
2547             8             7            13  ...             32   
2548             2            10            12  ...              3   
2549             1             0             0  ...             12   

      user_search_the_merchant  user_item_id_cnt  user_cat_id_cnt  \
2530                        16               102               22   
2531                        10               283              101   
2532                         6               283              101   
2533                        15                34               20   
2534                         9                56               20   
2535                        14                26               10   
2536                         2               120               58   
2537                         4               120               58   
2538                         1                 6                5   
2539                        46               144               39   
2540                         4               144               39   
2541                      

In [60]:
y=train.iloc[:,-3]
le=LabelEncoder()
le=le.fit(y)
le.classes_
#数据显示用户加入购物车数只有0和1，对数据存疑

array([0, 1], dtype=int64)

In [61]:
user_info_log[:5]

user_id  item_id  cat_id  merchant_id  brand_id  time_stamp  action_type  \
0   328862   323294     833         2882    2661.0         829            0   
1   328862   844400    1271         2882    2661.0         829            0   
2   328862   575153    1271         2882    2661.0         829            0   
3   328862   996875    1271         2882    2661.0         829            0   
4   328862  1086186    1271         1253    1049.0         829            0   

   age_range  gender  month  
0        6.0     1.0      8  
1        6.0     1.0      8  
2        6.0     1.0      8  
3        6.0     1.0      8  
4        6.0     1.0      8

In [62]:
#4、对于商家（点击总数、加入购物车数、收藏、购买数）
t=user_info_log.groupby(['merchant_id','action_type']).size().reset_index()

In [63]:
t[:5]

merchant_id  action_type     0
0            1            0  8739
1            1            2   519
2            1            3   323
3            2            0    35
4            2            2     4

In [64]:
t=pd.get_dummies(t,columns=['action_type'])

In [65]:
t[:5]

merchant_id     0  action_type_0  action_type_1  action_type_2  \
0            1  8739              1              0              0   
1            1   519              0              0              1   
2            1   323              0              0              0   
3            2    35              1              0              0   
4            2     4              0              0              1   

   action_type_3  
0              0  
1              0  
2              1  
3              0  
4              0

In [66]:
for i in range(0,4,1):
    t['action_type_'+str(i)]=t[0]*t['action_type_'+str(i)]

In [67]:
del t[0]

In [68]:
t=t.rename(columns={'action_type_0':'mer点击总数','action_type_1':'mer加入购物车数','action_type_2':'mer购买总数','action_type_3':'mer收藏总数'})

In [69]:
t[:5]

merchant_id  mer点击总数  mer加入购物车数  mer购买总数  mer收藏总数
0            1     8739          0        0        0
1            1        0          0      519        0
2            1        0          0        0      323
3            2       35          0        0        0
4            2        0          0        4        0

In [70]:
t=t.groupby(['merchant_id']).sum().reset_index()

In [71]:
t[:5]

merchant_id  mer点击总数  mer加入购物车数  mer购买总数  mer收藏总数
0            1     8739          0      519      323
1            2       35          0        4        2
2            3       29          0        0        4
3            4       27          0        7        4
4            5      125          0        8        7

In [72]:
train=train.merge(t,on=['merchant_id'])
test=test.merge(t,on=['merchant_id'])

In [73]:
train[:5]

user_id  merchant_id  label  age_range  gender  user_sum  user_month_5  \
0   374400          302      0        5.0     1.0       278             1   
1   336252          302      0        3.0     0.0       145             3   
2   305873          302      1        4.0     0.0       378            19   
3   189312         1760      0        4.0     0.0       237             0   
4   421338         1760      0        4.0     0.0       386             0   

   user_month_6  user_month_7  user_month_8  ...  user_merchant_id_cnt  \
0            16            30            98  ...                    57   
1            13             0             4  ...                    58   
2            48            24           114  ...                   118   
3             0             0             0  ...                    49   
4            21             7             7  ...                    79   

   user_brand_id_cnt  点击总数  加入购物车数  购买总数  收藏总数  mer点击总数  mer加入购物车数  mer购买总数  \
0               62.0   241       0    29     8       92          0       20   
1               57.0    70       0    12    63       92          0       20   
2              118.0   339       0    38     1       92          0       20   
3               45.0   228       0     9     0     1343          0      174   
4               77.0   376       0     8     2     1343          0      174   

   mer收藏总数  
0        1  
1        1  
2        1  
3       49  
4       49  

[5 rows x 26 columns]